apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: $TARGET_NAMESPACE

images:
  - name: $OHIFVIEWER_IMAGE_REPO/ohifviewer
    newTag: $OHIFVIEWER_IMAGE
resources:
  - manifests.yaml