name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - FluxV2
      - release/*

jobs:
  Build_Push_OHIFViewer_Image:
    #runs-on: ubuntu-latest
    name: Build and Push Image
    runs-on: [self-hosted, Linux, X64]
    env:
      SRC_FOLDER: ohifviewer
      AZ_ACR_NAME: ${{ secrets.AZ_ACR_NAME }}
    steps:
    - run: |
        sudo chown -R clemm /home/clemm/actions-runner/_work/
    - name: Checkout
      uses: actions/checkout@v3
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Docker Login to ACR
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.AZ_ACR_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Create Image Tag
      env:
        SOURCE_LOCATION: src 
        DOCKER_FILE: Dockerfile
        REPOSITORY: ohifviewer/ohifviewer
        TASKNAME: OHIFVIEWER_IMAGE
        IMAGE_TAG: ${{ github.sha }}   
      uses: Azure/cli@v1
      with:
        inlineScript:  |
          git config --global --add safe.directory '*'
          chmod +x $GITHUB_WORKSPACE/utils/buildContainerTemplate.sh
          $GITHUB_WORKSPACE/utils/buildContainerTemplate.sh -f $SRC_FOLDER \
                                                           -g $GITHUB_WORKSPACE \
                                                           -s $SOURCE_LOCATION \
                                                           -u $AZ_ACR_NAME \
                                                           -r $REPOSITORY \
                                                           -t $TASKNAME \
                                                           -d $DOCKER_FILE \
                                                           -i $IMAGE_TAG
    - run: |
        docker build -t ${{ secrets.AZ_ACR_NAME }}/ohifviewer/ohifviewer:${{ github.sha }} ./ohifviewer/src
        docker push ${{ secrets.AZ_ACR_NAME }}/ohifviewer/ohifviewer:${{ github.sha }}
    - name: Upload Image Tag
      uses: actions/upload-artifact@v3
      with:
        name: image_tags
        path: ${{ github.workspace }}/image_tags
    - name: Upload Manifests Templates
      uses: actions/upload-artifact@v3
      with:
        name: manifests
        path: ${{ github.workspace }}/ohifviewer/manifests
    - name: Upload Utils
      uses: actions/upload-artifact@v3
      with:
        name: utils
        path: ${{ github.workspace }}/utils
  Deploy_to_Stage:
    name: Deploy to Stage
    #runs-on: ubuntu-latest
    runs-on: [self-hosted, Linux, X64]
    needs: Build_Push_OHIFViewer_Image
    environment: ohifviewer-stage
    steps:
    - run: |
        sudo chown -R clemm /home/clemm/actions-runner/_work/
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Image Tags
      uses: actions/download-artifact@v3
      with:
        name: image_tags
        path: ${{ github.workspace }}/image_tags
    - name: Download Manifests Templates
      uses: actions/download-artifact@v3
      with:
        name: manifests
        path: ${{ github.workspace }}/manifests
    - name: Download Utils
      uses: actions/download-artifact@v3
      with:
        name: utils
        path: ${{ github.workspace }}/utils
    - name: Read Image Tags
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        for file in ${{ github.workspace }}/image_tags/*; do echo "::set-env name=${file##*/}::$(cat $file)"; done 
    - name: Generate Manifests
      run: |
        ${{ github.workspace }}/utils/generate-manifests.sh manifests gen_manifests
      env:
        TARGET_NAMESPACE: ${{ secrets.TARGET_NAMESPACE }}
        OHIFVIEWER_IMAGE_REPO: ${{ secrets.OHIFVIEWER_IMAGE_REPO }}
        SYSTEM_LABEL: ${{ secrets.SYSTEM_LABEL }}
    - name: Create PR
      run: |
        # Extract release number from the branch name
        # If it is a release branch, add a prefix to the manifests branch
        echo $GITHUB_REF | awk -F"release/" '{print $2}' 
        release_number=$(echo $GITHUB_REF | awk -F"release/" '{print $2}')
        [[ -z "$release_number" ]] || release_prefix=release/$release_number/  

        ${{ github.workspace }}/utils/create-pr.sh -s ${{ github.workspace }}/gen_manifests -d ${{ secrets.MANIFESTS_FOLDER }} -r ${{ secrets.MANIFESTS_REPO }} -b $(echo $release_prefix)${{ secrets.MANIFESTS_BRANCH }} -i $GITHUB_RUN_ID -t ${{ secrets.PAT }} -e ${{ secrets.ENVIRONMENT_NAME }}        

