name: Trigger auto deployment for ohifviewer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'ohifviewer/src/**'
    - '.github/workflows/ohifviewer-AutoDeployTrigger-be5d7ed7-8055-4d5b-8883-3dbb16de554e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ca946e310789acr.azurecr.io
          username: ${{ secrets.OHIFVIEWER_REGISTRY_USERNAME }}
          password: ${{ secrets.OHIFVIEWER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ca946e310789acr.azurecr.io/ohifviewer:${{ github.sha }}
          file: ohifviewer/src/Dockerfile
          context: ohifviewer/src/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.OHIFVIEWER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ohifviewer -g ACA --server ca946e310789acr.azurecr.io --username  ${{ secrets.OHIFVIEWER_REGISTRY_USERNAME }} --password ${{ secrets.OHIFVIEWER_REGISTRY_PASSWORD }}
            az containerapp update -n ohifviewer -g ACA --image ca946e310789acr.azurecr.io/ohifviewer:${{ github.sha }}
